---
# code: language=ansible
# - name: Create/update setting file
#   ansible.builtin.template:
#     src: wireguard.conf.j2
#     dest: /erc/wireguard/wireguard.conf
#     mode: "0644"
# - name: Add/update option setting
#   ansible.builtin.lineinfile:
#     path: /etc/wireguard/wireguard.conf
#     regexp: ^(#\\s+)?option_name=
#     line: option_name=option_value
# - name: Add/update custom setting
#   ansible.builtin.blockinfile:
#     path: /etc/wireguard/wireguard.conf
#     block: "{{ wireguard_extra_cfg | default('') }}"
