---
# code: language=ansible
- name: Create/update systemd unit file
  ansible.builtin.template:
    src: wireguard.service.j2
    dest: /lib/systemd/system/wireguard.service
    mode: "0644"
  notify: restart wireguard
- name: Service wireguard is active and enabled on system startup
  ansible.builtin.systemd_service:
    name: wireguard
    state: started
    enabled: true
# - name: allow wireguard port
#   community.general.ufw:
#     rule: allow
#     port: "123456"
