---
# code: language=ansible
# - name: Set Install version variable
#   when: wireguard_version == 'latest'
#   block:
#     - name: Get latest release
#       ansible.builtin.uri:
#         url: https://api.github.com/repos/{{ wireguard_repo_owner }}/{{ wireguard_repo_name }}/releases/latest
#         headers:
#           Accept: application/vnd.github+json
#       register: latest_releases
#     - name: Set package version variable
#       ansible.builtin.set_fact:
#         wireguard_version: "{{ latest_releases.json.tag_name }}"
# - name: Set pckage file variable
#   ansible.builtin.set_fact:
#     package_file: wireguard_{{ wireguard_version[1:] }}_{{ architecture_files[ansible_facts['architecture']] }}.deb
#   vars:
#     architecture_files:
#       x86_64: amd64
#       aarch64: arm64
# - name: Install wireguard
#   ansible.builtin.apt:
#     deb: https://github.com/{{ wireguard_repo_owner }}/{{ wireguard_repo_name }}/releases/download/{{ wireguard_version }}/{{ package_file }}
- name: Install wireguard packages
  ansible.builtin.apt:
    name: "{{ wireguard_packages }}"
